### ISSUE TITLE
Update for mini oled kit does not work

### ISSUE THREAD

**Issue by RP250258** [audiophonics/RaspDacMini#2]
I have install as mention, get o lot of errors

login as: pi
pi@192.168.2.11's password:
RaspiOS 10.6 | 5.4.77-v7l+ #1371 | armv7l (32-bit)
Hardware: Pi-4B 1.4 4GB

                      ____     __        ____
          __ _  ___  / __ \___/ /__     /_  /
         /  ' \/ _ \/ /_/ / _  / -_)     / /
        /_/_/_/\___/\____/\_,_/\__/     /_/

                 moOde audio player
              Release 7.3.0 2021-06-25
                (C) 2014 Tim Curtis

The programs included with moOde are free software; the
exact distribution terms for each program are described
in the individual files in /usr/share/doc/*/copyright.
Moode comes with absolutely no warranties expressed or
implied, or any other guarantees.

pi@moode:~ $ git clone http://github.com/audiophonics/RaspDacMini
Cloning into 'RaspDacMini'...
warning: redirecting to https://github.com/audiophonics/RaspDacMini/
remote: Enumerating objects: 255, done.
remote: Counting objects: 100% (255/255), done.
remote: Compressing objects: 100% (232/232), done.
remote: Total 255 (delta 80), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (255/255), 14.67 MiB | 3.04 MiB/s, done.
Resolving deltas: 100% (80/80), done.
pi@moode:~ $ cd RaspDacMini
pi@moode:~/RaspDacMini $ cd moode
pi@moode:~/RaspDacMini/moode $ sudo bash install.sh
***   Installation of RaspDac Mini OLED for moOde
***   _____________________________________
* Installing : Audiophonics ToolSet (web interface)
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libc-ares2 libnode64 nodejs-doc
Suggested packages:
  npm
The following NEW packages will be installed:
  libc-ares2 libnode64 nodejs nodejs-doc
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 6,003 kB of archives.
After this operation, 27.4 MB of additional disk space will be used.
Err:1 http://raspbian.raspberrypi.org/raspbian buster/main armhf libc-ares2 armhf 1.14.0-1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:2 http://raspbian.raspberrypi.org/raspbian buster/main armhf libnode64 armhf 10.21.0~dfsg-1~deb10u1+rpi1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:3 http://raspbian.raspberrypi.org/raspbian buster/main armhf nodejs armhf 10.21.0~dfsg-1~deb10u1+rpi1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:4 http://raspbian.raspberrypi.org/raspbian buster/main armhf nodejs-doc all 10.21.0~dfsg-1~deb10u1+rpi1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/c/c-ares/libc-ares2_1.14.0-1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/n/nodejs/libnode64_10.21.0~dfsg-1~deb10u1+rpi1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/n/nodejs/nodejs_10.21.0~dfsg-1~deb10u1+rpi1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/n/nodejs/nodejs-doc_10.21.0~dfsg-1~deb10u1+rpi1_all.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Audiophonics ToolSet service enabled & started
* End of installation : Audiophonics ToolSet (web interface) - no reboot required
* Installing : Basic instructions set for Audiophonics ES90X8 DAC
* End of installation :Basic instructions set for Audiophonics ES90X8 DAC
* Installing : RaspDac Mini OLED
installing nodejs env and dependencies
grep: /etc/modprobe.d/spidev.conf: No such file or directory
OLED service enabled ( /etc/systemd/system/oled.service )
*End of installation : RaspDac Mini OLED (spidev module is NOT loaded : a reboot is required)
* Installing : RaspdacMini Oled Remote
Created symlink /etc/systemd/system/multi-user.target.wants/irexec.service → /lib/systemd/system/irexec.service.
Synchronizing state of lircd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable lircd
* End of installation : RaspdacMini Oled  - reboot required
* End of installation : RaspDac Mini OLED for moOde
started at 03:45:55 finished at 03:47:10

**Comment by RP250258** [comment]
could you please help me out !!!

I have the old version Mini kit with RPI3b

Hen

**Comment by audiophonics** [comment]
Hello

moode current buster version is currently oldstable repository structure. 
Try doing 
`sudo apt-get update --allow-releaseinfo-change` 
prior to running the script

**Comment by RP250258** [comment]
still the same 

tell me step by step what to do?

login as: pi
pi@192.168.2.20's password:
RaspiOS 10.6 | 5.4.77-v7l+ #1371 | armv7l (32-bit)
Hardware: Pi-4B 1.4 4GB

                      ____     __        ____
          __ _  ___  / __ \___/ /__     /_  /
         /  ' \/ _ \/ /_/ / _  / -_)     / /
        /_/_/_/\___/\____/\_,_/\__/     /_/

                 moOde audio player
              Release 7.3.0 2021-06-25
                (C) 2014 Tim Curtis


The programs included with moOde are free software; the
exact distribution terms for each program are described
in the individual files in /usr/share/doc/*/copyright.
Moode comes with absolutely no warranties expressed or
implied, or any other guarantees.

pi@moode:~ $ sudo apt-get update
Get:1 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Get:2 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
Get:3 http://archive.raspberrypi.org/debian buster/main armhf Packages [393 kB]
Reading package lists... Done
E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
pi@moode:~ $ git clone http://github.com/audiophonics/RaspDacMini
Cloning into 'RaspDacMini'...
warning: redirecting to https://github.com/audiophonics/RaspDacMini/
remote: Enumerating objects: 255, done.
remote: Counting objects: 100% (255/255), done.
remote: Compressing objects: 100% (232/232), done.
remote: Total 255 (delta 80), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (255/255), 14.67 MiB | 2.83 MiB/s, done.
Resolving deltas: 100% (80/80), done.
pi@moode:~ $ cd RaspDacMini
pi@moode:~/RaspDacMini $ cd moode
pi@moode:~/RaspDacMini/moode $ sudo bash install.sh
***   Installation of RaspDac Mini OLED for moOde
***   _____________________________________
* Installing : Audiophonics ToolSet (web interface)
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libc-ares2 libnode64 nodejs-doc
Suggested packages:
  npm
The following NEW packages will be installed:
  libc-ares2 libnode64 nodejs nodejs-doc
0 upgraded, 4 newly installed, 0 to remove and 79 not upgraded.
Need to get 6,003 kB of archives.
After this operation, 27.4 MB of additional disk space will be used.
Err:1 http://raspbian.raspberrypi.org/raspbian buster/main armhf libc-ares2 armhf 1.14.0-1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:2 http://raspbian.raspberrypi.org/raspbian buster/main armhf libnode64 armhf 10.21.0~dfsg-1~deb10u1+rpi1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:3 http://raspbian.raspberrypi.org/raspbian buster/main armhf nodejs armhf 10.21.0~dfsg-1~deb10u1+rpi1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:4 http://raspbian.raspberrypi.org/raspbian buster/main armhf nodejs-doc all 10.21.0~dfsg-1~deb10u1+rpi1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/c/c-ares/libc-ares2_1.14.0-1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/n/nodejs/libnode64_10.21.0~dfsg-1~deb10u1+rpi1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/n/nodejs/nodejs_10.21.0~dfsg-1~deb10u1+rpi1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/n/nodejs/nodejs-doc_10.21.0~dfsg-1~deb10u1+rpi1_all.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Audiophonics ToolSet service enabled & started
* End of installation : Audiophonics ToolSet (web interface) - no reboot required
* Installing : Basic instructions set for Audiophonics ES90X8 DAC
* End of installation :Basic instructions set for Audiophonics ES90X8 DAC
* Installing : RaspDac Mini OLED
installing nodejs env and dependencies
grep: /etc/modprobe.d/spidev.conf: No such file or directory
OLED service enabled ( /etc/systemd/system/oled.service )
*End of installation : RaspDac Mini OLED (spidev module is NOT loaded : a reboot is required)
* Installing : RaspdacMini Oled Remote
Created symlink /etc/systemd/system/multi-user.target.wants/irexec.service → /lib/systemd/system/irexec.service.
Synchronizing state of lircd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable lircd
* End of installation : RaspdacMini Oled  - reboot required
* End of installation : RaspDac Mini OLED for moOde
started at 05:37:00 finished at 05:38:04
pi@moode:~/RaspDacMini/moode $

**Comment by audiophonics** [comment]
There is no point in continuing if
 
`sudo apt-get update `

returns this error : 

_E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'_


You have to input the whole command : 
`sudo apt-get update --allow-releaseinfo-change`

(don't forget the "_--allow-releaseinfo-change_" )

**Comment by RP250258** [comment]
it works many thanks
how can a change the following

swich off the screensaver an the snake screen
and i play with 0 DB 

thanks

**Comment by RP250258** [comment]
when I select 0 dB the screen freeze with the Audiophonics logo !! and don't go further

**Comment by audiophonics** [comment]
Well, the script was never meant to deal with 0db as MPD output since the hardware volume achieves the same sound quality thanks to ES9038 internal hardware volume controller. 

Plus most distro (including moode) skip loading some ALSA handles for DAC control in 0dB, which prevents addressing most DAC options (such as picking a reconstruction filter and can also cause some trouble in properly detecting & displaying the SPDIF out being active instead of the I2S). 

I would suggest using hardware volume output mode in any situation. Yet I still added a basic support for 0db mode in the display driver if needed for whatever other reason. 

I also completed the screen handle in http://moode:4150 so you can just input 0 in the _Delay (deep sleep)_ field (which will result in the screen turning off instantly instead of displaying the snake screen saver). 

If needed, an updated image file is availble on [audiophonics blog](https://www.audiophonics.fr/blog-diy-audio/23-.html#rdm)

**Comment by RP250258** [comment]
Thanks for the update, this is working much better...
I have change the small Oled display for a bigger 2.4 inch it works but cannot change the contrast

https://nl.aliexpress.com/item/32871927644.html?spm=a2g0o.cart.0.0.29613c00JfpIEl&mp=1

is there a way to make the contrast brighter for this display
thanks in advance

**Comment by RP250258** [comment]
Dear Sir, 
How can a select to keep the display always on, when selecting a higher level 
FI 5 years = 157784630 sec. in Moode:4150 the display is going black after stop

can you please change that for me?

many thanks

**Comment by audiophonics** [comment]
> Dear Sir, How can a select to keep the display always on, when selecting a higher level FI 5 years = 157784630 sec. in Moode:4150 the display is going black after stop
> 
> can you please change that for me?
> 
> many thanks

I need some clarifications here. 
Do you want the display to remain always on, regardless of what is happening in the player ?

**Comment by RP250258** [comment]
Yes even when the player is not playing you see the time.

Thanks

**Comment by RP250258** [comment]
> Yes even when the player is not playing you see the time.
> 
> Thanks

Yes please display always on

**Comment by RP250258** [comment]
Is it possible to use the old oled source version 6.3 for the 7.40 moode version?

I lake that display much more the the new one
startup with the time 

Thanks

**Comment by RP250258** [comment]
hi i have try this link from your website but it does not work with 7.30

http://forum.audiophonics.fr/viewtopic.php?f=12&t=2935

can you please inform me step by step what to do?

thx

**Comment by audiophonics** [comment]
I just tested this on a fresh install and doing this works : 
` sudo apt-get update`
` sudo apt install lirc`
`sudo cp -r lirc  /etc/`
`sudo bash -c 'if ! grep -q "dtoverlay=gpio-ir,gpio_pin=4" "/boot/config.txt"; then echo "dtoverlay=gpio-ir,gpio_pin=4"  >> /boot/config.txt ; fi; '`
`sudo bash -c 'if ! grep -q spi-dev "/etc/modules"; then echo "spi-dev" >> /etc/modules ;fi ;'`
`sudo bash -c 'if ! grep -q dtparam=spi=on "/boot/config.txt"; then echo "dtparam=spi=on"  >> /boot/config.txt ; fi '`
`chmod +x script_update_python.sh`
`./script_update_python.sh`
`sudo cp oled.service /etc/systemd/system/`
`sudo systemctl enable oled.service`

- Then go in moOde UI
- Select DAC ES90x8 in moode UI
- configure hardware mixer in MPD settings
- reboot

**Comment by RP250258** [comment]
Try you code

fresh instal moodeaudio 7.40
see what happen

RaspiOS 10.6 | 5.4.77-v7+ #1371 | armv7l (32-bit)
Hardware: Pi-3B 1.2 1GB

                      ____     __        ____
          __ _  ___  / __ \___/ /__     /_  /
         /  ' \/ _ \/ /_/ / _  / -_)     / /
        /_/_/_/\___/\____/\_,_/\__/     /_/

                 moOde audio player
              Release 7.4.0 2021-09-24
                (C) 2014 Tim Curtis


The programs included with moOde are free software; the
exact distribution terms for each program are described
in the individual files in /usr/share/doc/*/copyright.
Moode comes with absolutely no warranties expressed or
implied, or any other guarantees.

pi@moode:~ $ sudo apt-get update
Get:1 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Get:3 http://archive.raspberrypi.org/debian buster/main armhf Packages [393 kB]
Reading package lists... Done
E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
pi@moode:~ $ sudo apt install lirc
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  gir1.2-atk-1.0 gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-gtk-3.0
  gir1.2-pango-1.0 gir1.2-vte-2.91 liblirc-client0 liblirc0 libpangoxft-1.0-0
  libvte-2.91-0 libvte-2.91-common python3-yaml
Suggested packages:
  lirc-compat-remotes lirc-drv-irman lirc-doc lirc-x setserial ir-keytable
The following NEW packages will be installed:
  gir1.2-atk-1.0 gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-gtk-3.0
  gir1.2-pango-1.0 gir1.2-vte-2.91 liblirc-client0 liblirc0 libpangoxft-1.0-0
  libvte-2.91-0 libvte-2.91-common lirc python3-yaml
0 upgraded, 13 newly installed, 0 to remove and 79 not upgraded.
Need to get 2,965 kB of archives.
After this operation, 6,835 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://archive.raspberrypi.org/debian buster/main armhf gir1.2-gtk-3.0 armhf 3.24.5-1+rpt2 [252 kB]
Get:2 http://archive.raspberrypi.org/debian buster/main armhf liblirc-client0 armhf 0.10.1-6.3~deb10u1+rpt1 [68.1 kB]
Get:3 http://archive.raspberrypi.org/debian buster/main armhf liblirc0 armhf 0.10.1-6.3~deb10u1+rpt1 [121 kB]
Get:4 http://archive.raspberrypi.org/debian buster/main armhf lirc armhf 0.10.1-6.3~deb10u1+rpt1 [490 kB]
Get:5 http://mirror.nl.leaseweb.net/raspbian/raspbian buster/main armhf gir1.2-atk-1.0 armhf 2.30.0-2 [25.3 kB]
Get:6 http://mirror.serverius.net/raspbian/raspbian buster/main armhf gir1.2-freedesktop armhf 1.58.3-2 [20.3 kB]
Get:7 http://mirror.nl.leaseweb.net/raspbian/raspbian buster/main armhf gir1.2-gdkpixbuf-2.0 armhf 2.38.1+dfsg-1 [18.3 kB]
Get:8 http://mirror.serverius.net/raspbian/raspbian buster/main armhf libpangoxft-1.0-0 armhf 1.42.4-8~deb10u1 [47.6 kB]
Get:9 http://mirror.serverius.net/raspbian/raspbian buster/main armhf gir1.2-pango-1.0 armhf 1.42.4-8~deb10u1 [55.8 kB]
Get:10 http://mirror.nl.leaseweb.net/raspbian/raspbian buster/main armhf libvte-2.91-common all 0.54.2-2 [563 kB]
Get:11 http://mirror.nl.leaseweb.net/raspbian/raspbian buster/main armhf libvte-2.91-0 armhf 0.54.2-2 [663 kB]
Get:12 http://mirror.serverius.net/raspbian/raspbian buster/main armhf gir1.2-vte-2.91 armhf 0.54.2-2 [529 kB]
Get:13 http://mirror.serverius.net/raspbian/raspbian buster/main armhf python3-yaml armhf 3.13-2 [111 kB]
Fetched 2,965 kB in 2s (1,970 kB/s)
Selecting previously unselected package gir1.2-atk-1.0:armhf.
(Reading database ... 68400 files and directories currently installed.)
Preparing to unpack .../00-gir1.2-atk-1.0_2.30.0-2_armhf.deb ...
Unpacking gir1.2-atk-1.0:armhf (2.30.0-2) ...
Selecting previously unselected package gir1.2-freedesktop:armhf.
Preparing to unpack .../01-gir1.2-freedesktop_1.58.3-2_armhf.deb ...
Unpacking gir1.2-freedesktop:armhf (1.58.3-2) ...
Selecting previously unselected package gir1.2-gdkpixbuf-2.0:armhf.
Preparing to unpack .../02-gir1.2-gdkpixbuf-2.0_2.38.1+dfsg-1_armhf.deb ...
Unpacking gir1.2-gdkpixbuf-2.0:armhf (2.38.1+dfsg-1) ...
Selecting previously unselected package libpangoxft-1.0-0:armhf.
Preparing to unpack .../03-libpangoxft-1.0-0_1.42.4-8~deb10u1_armhf.deb ...
Unpacking libpangoxft-1.0-0:armhf (1.42.4-8~deb10u1) ...
Selecting previously unselected package gir1.2-pango-1.0:armhf.
Preparing to unpack .../04-gir1.2-pango-1.0_1.42.4-8~deb10u1_armhf.deb ...
Unpacking gir1.2-pango-1.0:armhf (1.42.4-8~deb10u1) ...
Selecting previously unselected package gir1.2-gtk-3.0:armhf.
Preparing to unpack .../05-gir1.2-gtk-3.0_3.24.5-1+rpt2_armhf.deb ...
Unpacking gir1.2-gtk-3.0:armhf (3.24.5-1+rpt2) ...
Selecting previously unselected package libvte-2.91-common.
Preparing to unpack .../06-libvte-2.91-common_0.54.2-2_all.deb ...
Unpacking libvte-2.91-common (0.54.2-2) ...
Selecting previously unselected package libvte-2.91-0:armhf.
Preparing to unpack .../07-libvte-2.91-0_0.54.2-2_armhf.deb ...
Unpacking libvte-2.91-0:armhf (0.54.2-2) ...
Selecting previously unselected package gir1.2-vte-2.91:armhf.
Preparing to unpack .../08-gir1.2-vte-2.91_0.54.2-2_armhf.deb ...
Unpacking gir1.2-vte-2.91:armhf (0.54.2-2) ...
Selecting previously unselected package liblirc-client0:armhf.
Preparing to unpack .../09-liblirc-client0_0.10.1-6.3~deb10u1+rpt1_armhf.deb ...
Unpacking liblirc-client0:armhf (0.10.1-6.3~deb10u1+rpt1) ...
Selecting previously unselected package liblirc0:armhf.
Preparing to unpack .../10-liblirc0_0.10.1-6.3~deb10u1+rpt1_armhf.deb ...
Unpacking liblirc0:armhf (0.10.1-6.3~deb10u1+rpt1) ...
Selecting previously unselected package lirc.
Preparing to unpack .../11-lirc_0.10.1-6.3~deb10u1+rpt1_armhf.deb ...
Unpacking lirc (0.10.1-6.3~deb10u1+rpt1) ...
Selecting previously unselected package python3-yaml.
Preparing to unpack .../12-python3-yaml_3.13-2_armhf.deb ...
Unpacking python3-yaml (3.13-2) ...
Setting up gir1.2-freedesktop:armhf (1.58.3-2) ...
Setting up libpangoxft-1.0-0:armhf (1.42.4-8~deb10u1) ...
Setting up liblirc0:armhf (0.10.1-6.3~deb10u1+rpt1) ...
Setting up libvte-2.91-common (0.54.2-2) ...
Setting up gir1.2-gdkpixbuf-2.0:armhf (2.38.1+dfsg-1) ...
Setting up gir1.2-atk-1.0:armhf (2.30.0-2) ...
Setting up python3-yaml (3.13-2) ...
Setting up libvte-2.91-0:armhf (0.54.2-2) ...
Setting up gir1.2-pango-1.0:armhf (1.42.4-8~deb10u1) ...
Setting up liblirc-client0:armhf (0.10.1-6.3~deb10u1+rpt1) ...
Setting up lirc (0.10.1-6.3~deb10u1+rpt1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/lircd.service → /lib/systemd/system/lircd.service.
Created symlink /etc/systemd/system/sockets.target.wants/lircd.socket → /lib/systemd/system/lircd.socket.
Setting up gir1.2-gtk-3.0:armhf (3.24.5-1+rpt2) ...
Setting up gir1.2-vte-2.91:armhf (0.54.2-2) ...
Processing triggers for systemd (241-7~deb10u4+rpi1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
pi@moode:~ $ sudo cp -r lirc /etc/
cp: cannot stat 'lirc': No such file or directory

**Comment by audiophonics** [comment]
Hello, you are supposed to extract this archive on the /home/pi directory beforehand.
https://mega.nz/file/it1m1AwR#vR-la2mquI7xe3UyUwKjJZ5uLwXAD7_gZYJNyGWkeB0
