### ISSUE TITLE
Is there a way to set Jitter correction?

### ISSUE THREAD

**Issue by McDin** [audiophonics/RaspDacMini#3]
I have very bad Jitter problems with toslink and Samsung TV. Several other threads with other dacs can solve it by changing the Jitter correction (dpll settings) to an higher value. Is there any possibility to do so for RaspDacMini?

**Comment by audiophonics** [comment]
We had a look at this issue and I am sorry to say that it is totally out of our reach to make a clean fix for this.

It would need us to build a second firmware with overall degraded audio performance (ultra wide jitter rejection), distribute and support a solution to push it into the device's chip. Plus our circuit was designed to be small enough to fit on a Raspberry Pi and has consequently very little margin for this type of changes. 

There also have been plenty of TV series having all kind of troubles with SPDIF and we cannot simply edit a new firmware to accomodate every flaw or substandard digital implementation.
